import fs from "node:fs/promises";
import path from "node:path";
import webpush, { type PushSubscription } from "web-push";
import { bus } from "./bus.ts";
import { env, REPO_ROOT } from "./env.ts";
import { lock, readJson, writeJson } from "./fsutil.ts";
import { record } from "./monitor.ts";
import { paths } from "./store.ts";

/**
 * Web Push (free: browsers' own push services; payloads are end-to-end encrypted).
 * VAPID keys are generated once and kept in .env. Subscriptions live in agent-home/push/
 * (device config: kept across Reset). Pushes are skipped while the app is visible on a device —
 * the in-app toast covers that case.
 */
const SUBS = () => path.join(paths.home, "push", "subscriptions.json");
interface StoredSub { subscription: PushSubscription; added_at: string; ua?: string }

let ready: Promise<string> | null = null;

/** Ensure VAPID keys exist (generate + append to .env on first use). Returns the public key. */
export function vapidPublicKey(): Promise<string> {
  ready ??= (async () => {
    let pub = process.env.VAPID_PUBLIC_KEY;
    let priv = process.env.VAPID_PRIVATE_KEY;
    if (!pub || !priv) {
      const k = webpush.generateVAPIDKeys();
      pub = k.publicKey;
      priv = k.privateKey;
      await fs.appendFile(path.join(REPO_ROOT, ".env"), `\n# Web Push (generated by the runner)\nVAPID_PUBLIC_KEY=${pub}\nVAPID_PRIVATE_KEY=${priv}\n`);
      process.env.VAPID_PUBLIC_KEY = pub;
      process.env.VAPID_PRIVATE_KEY = priv;
      console.log("[push] generated VAPID keys into .env");
    }
    webpush.setVapidDetails(process.env.VAPID_SUBJECT || "mailto:canvas-agent@example.com", pub, priv);
    return pub;
  })();
  return ready;
}

const loadSubs = async () => (await readJson<StoredSub[]>(SUBS())) ?? [];

export async function addSubscription(subscription: PushSubscription, ua?: string) {
  await lock("push", async () => {
    const subs = (await loadSubs()).filter((s) => s.subscription.endpoint !== subscription.endpoint);
    subs.push({ subscription, added_at: new Date().toISOString(), ua: ua?.slice(0, 120) });
    await writeJson(SUBS(), subs);
  });
}

export async function removeSubscription(endpoint: string) {
  await lock("push", async () => writeJson(SUBS(), (await loadSubs()).filter((s) => s.subscription.endpoint !== endpoint)));
}

export const subscriptionCount = async () => (await loadSubs()).length;

export interface PushMessage { title: string; body: string; url?: string; tag?: string }

/** Send to every subscribed device unless the app is visible somewhere (or force). */
export async function pushAll(m: PushMessage, opts: { force?: boolean } = {}): Promise<{ sent: number; skipped?: string }> {
  if (!opts.force && bus.anyVisible()) return { sent: 0, skipped: "app is open" };
  const subs = await loadSubs();
  if (!subs.length) return { sent: 0, skipped: "no devices subscribed" };
  await vapidPublicKey();
  let sent = 0;
  const dead: string[] = [];
  await Promise.all(
    subs.map(async (s) => {
      try {
        await webpush.sendNotification(s.subscription, JSON.stringify(m), { TTL: 6 * 3600, urgency: "high", topic: m.tag?.slice(0, 32).replace(/[^\w-]/g, "") || undefined });
        sent++;
      } catch (err) {
        const code = (err as { statusCode?: number }).statusCode;
        if (code === 404 || code === 410) dead.push(s.subscription.endpoint); // unsubscribed / expired
        else console.warn("[push] send failed", code, (err as Error).message);
      }
    }),
  );
  for (const e of dead) await removeSubscription(e);
  record({ kind: "system", title: `push: ${m.title}`, detail: `${m.body.slice(0, 120)} → ${sent} device(s)${dead.length ? `, ${dead.length} expired removed` : ""}`, ok: sent > 0 });
  return { sent };
}

export const pushConfigured = () => !!env.RUNNER_TOKEN; // always available; keys are generated on demand
